---

build:
  stage: build
  image: cimesi/janez:builder
  script:
    - make build
  retry: 2
  artifacts:
    paths:
      - public
    expire_in: 1 week

push:
  stage: deploy
  image: cimesi/janez:pusher
  variables:
    S3_SECRET_KEY: secret
  script:
    - make publish
  retry: 2
