---

baseURL: https://janez2.cime.si/
languageCode: en-us
title: Janez Cimerman
theme: 
  - vanilla-bootstrap
copyright: ©2020 Janez Cimerman.

enableRobotsTXT: false

menu:
  nav:
  - name: Home
    pre: home
    url: /
    weight: 1
  # - name: Tags
  #   pre: tag
  #   url: /tags/
  #   weight: 3
  - name: GitHub
    pre: github
    url: /github/
    weight: 4
  - name: About
    pre: smile
    url: /about/
    weight: 5

params:
  homePicture: logo_transparent.png
  backgroundPicture: nasaEarth.jpg
  style: dark
  dateFormat: "2006-01-02"
  homeText: Eat sleap make repeat.
  footerText: 2020 JanezCimerman. Made with [Hugo](https://gohugo.io/) & [Vanilla](https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme)
  hideFooter: false
  mainSections:
    - post
#   logo: logo.png  # if you have a logo png
#   slogan: Projects log
#   license: ""  # CC License
#   nav:
#     showCategories: false       # /categories/
#     showTags: true             # /tags/
#     custom:
#       title: "About"
#       url: "/about"

outputs:
  home:
    - HTML
    - JSON
  page:
    - HTML
