---

backend:
  name: gitlab
  repo: gregor/janez
  branch: master # Branch to update (optional; defaults to master)
  auth_type: implicit # Required for implicit grant
  app_id: f114592102c5ab5c558108b668e28b1f58462a4d7c0cc8487083203de7f221af # Application ID from your GitLab settings
  api_root: https://git.cime.si/api/v4
  base_url: https://git.cime.si
  auth_endpoint: oauth/authorize
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Cover photo", name: "cover", widget: "image"}
      - {label: "Draft", name: "draft", widget: "string", default: "true"}
      # - {label: "Categories", name: "categories", required: false, widget: "list"}
      # - {label: "Tags", name: "tags", required: false, widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
